layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# Site settings
title: Moran Xu | Algorithm Engineer
description: >-
  Personal website for Moran Xu, Algorithm Engineer specializing in deep learning and computer vision 
  at Carl Zeiss X-Ray Microscopy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  googlescholar: Pz5A2ZkAAAAJ
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: moran-xu-166641224
  website: https://moranxu.github.io
  email: xumoran34@gmail.com
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/deep-learning/deep-learning.png

  - name: Computer Vision 
    web_url: https://github.com/topics/computer-vision

  - name: X-ray Imaging
    web_url: https://github.com/topics/xray

author:
  name: Moran Xu
  bio: >
    Algorithm Engineer experienced in deep learning, computer vision, and X-ray reconstruction. 
    MS in Computer Science from Washington University in St. Louis.
    Currently working at Carl Zeiss X-Ray Microscopy, Inc. developing cutting-edge image processing algorithms.
  location: Dublin, CA
  email: xumoran34@gmail.com